app:
    resource: '@AppBundle/Controller/'
    type: annotation

login:
    path: '/login'
    methods: 'post'

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing/swaggerui.xml"
    prefix:   /api/doc